#104 migrate autoscaling api version from deprecated
chatwoot/charts pull request #105
Opened 2023-07-21 05:51 UTC by razorman8669

#104

2023-07-26 08:51 UTC, vishnu-narayanan requested changes
Hey @razorman8669, Thank you for the PR.

Could you please make the following changes?

1. Make the `apiVersion` configurable so that older k8s installations are not affected. Create a new value `autoscaling.apiVersion` with default value `autoscaling/v2`. 
2. Increment the Chart version

2023-07-26 08:51 UTC, vishnu-narayanan commented on charts/chatwoot/templates/web-hpa.yaml
> +apiVersion: autoscaling/v2
```suggestion
apiVersion: {{ .Values.autoscaling.apiVersion }}
```

2023-07-26 08:51 UTC, vishnu-narayanan commented on charts/chatwoot/templates/worker-hpa.yaml
> +apiVersion: autoscaling/v2
```suggestion
apiVersion: {{ .Values.autoscaling.apiVersion }}
```

2023-07-27 01:16 UTC, razorman8669 commented
@vishnu-narayanan I made the suggested changes.  I bumped the minor version since this is technically a breaking change for users of older kubernetes versions (pre v1.23)

2023-07-27 11:12 UTC, vishnu-narayanan approved these changes

2023-07-27 11:13 UTC, merged

2023-07-27 11:13 UTC, vishnu-narayanan commented
@razorman8669 Thank you for the changes 🙇